# Generated by Django 2.2.4 on 2019-09-17 09:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190917_0904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postpage',
            name='categories',
        ),
        migrations.CreateModel(
            name='PageCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_pages', to='blog.BlogCategory')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='blog.PostPage')),
            ],
            options={
                'unique_together': {('page', 'blog_category')},
            },
        ),
    ]
