# Generated by Django 2.2.4 on 2019-09-28 09:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0006_postpage_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='cover_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.Image'),
        ),
        migrations.AddField(
            model_name='postpage',
            name='short_description',
            field=wagtail.core.fields.RichTextField(blank=True),
        ),
    ]
