# Generated by Django 2.2.4 on 2019-09-29 11:41

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20190928_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='postpage',
            name='categories',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='blog.BlogCategory'),
        ),
        migrations.DeleteModel(
            name='PageCategory',
        ),
    ]
